# Generated by Django 4.1.3 on 2022-11-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programming_language', models.CharField(max_length=20)),
                ('frontend', models.CharField(max_length=20)),
                ('backend', models.CharField(max_length=20)),
            ],
        ),
    ]
