# Generated by Django 4.1.3 on 2022-11-25 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_studentactivity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentActivity',
        ),
    ]
