# Generated by Django 4.1.3 on 2022-11-25 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_studentactivity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentactivity',
            old_name='name',
            new_name='detail',
        ),
    ]
