# Generated by Django 4.1.3 on 2022-11-25 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_rename_name_studentactivity_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentactivity',
            name='detail',
        ),
    ]
