# Generated by Django 4.1.3 on 2022-11-27 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.message'),
        ),
    ]
