# Generated by Django 4.1.3 on 2022-11-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_room_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='message',
        ),
        migrations.AddField(
            model_name='room',
            name='message',
            field=models.ManyToManyField(blank=True, null=True, to='base.message'),
        ),
    ]
